#!/bin/bash
##
# Notification of First Boot Jobs

set -eu

start() {
	clear
	echo "" > /dev/tty1
	echo "XenServer Firstboot configuration beginning." > /dev/tty1
	echo "The Storage Volumes are now being set up." > /dev/tty1
	echo "The server maybe rebooted more than once when this has completed..." > /dev/tty1
}

case $1 in
    start)  start ;;
esac	
