#!/bin/bash
##
# Run openstack specific firstboot tasks

set -eu

. ${XENSOURCE_INVENTORY}

CONFIGURATION="${FIRSTBOOT_DATA_DIR}/default-storage.conf"
UPGRADE="false"
[ -r ${FIRSTBOOT_DATA_DIR}/host.conf ] && . ${FIRSTBOOT_DATA_DIR}/host.conf

start() {
    [ "$UPGRADE" = true ] && return 0
    if [ -e ${CONFIGURATION} ]; then
        source ${CONFIGURATION}
        SR=$($XE sr-list type=$TYPE params=uuid --minimal | cut -f1 -d,)
	HOSTID=$($XE host-list --minimal)
    fi

	# create /mnt symlink to reside in SR-REPO for openstack code
	rm -rf /mnt
	mkdir /var/run/sr-mount/$SR/mnt
	ln -s /var/run/sr-mount/$SR/mnt /mnt

        # create /images symlink to reside in SR-REPO for migrations
        rm -rf /images
        mkdir /var/run/sr-mount/$SR/images
        ln -s /var/run/sr-mount/$SR/images /images

        # create iso sr 
        mkdir /var/run/sr-mount/$SR/iso
        xe sr-create name-label="Local ISO SR" type=iso device-config:legacy_mode=true device-config:location=/var/run/sr-mount/$SR/iso content-type=iso
        ISOSR=`xe sr-list name-label="Local ISO SR" --minimal`
        xe sr-param-set uuid=$ISOSR other-config:i18n-key=local-storage-iso

	# Prepare for AMI type images
	LOCALPATH="/var/run/sr-mount/$SR/os-guest-kernels"
	mkdir -p "$LOCALPATH"
	ln -s "$LOCALPATH" /boot/guest

	# Activate host metrics
	xe host-param-add param-name=other-config uuid=$HOSTID rrd_update_interval=2

	# install the XenAPI plug-ins
	NOVA_ZIPBALL=$(mktemp)
	NOVA_SOURCES=$(mktemp -d)
	wget -qO "$NOVA_ZIPBALL" https://github.com/openstack/nova/archive/master.zip
	unzip -q "$NOVA_ZIPBALL" -d "$NOVA_SOURCES"
	PLUGINPATH=$(find $NOVA_SOURCES -path '*/xapi.d/plugins' -type d -print)
	cp $PLUGINPATH/* /etc/xapi.d/plugins/

	# And VIF Isolation Rules
	VIFPATH=$(find $NOVA_SOURCES -path '*/xenserver/networking' -type d -print)
	cp $VIFPATH/etc/init.d/* /etc/init.d/
	cp $VIFPATH/etc/sysconfig/* /etc/sysconfig/
	cp $VIFPATH/etc/udev/rules.d/*  /etc/udev/rules.d/
	cp $VIFPATH/etc/xensource/scripts/* /etc/xensource/scripts/
	chkconfig host-rules on
	/etc/init.d/host-rules start

	# install console logrotate script
	LOG_PATH=$(find $NOVA_SOURCES -path '*/tools/xenserver' -type d     -print)
	cp $LOG_PATH/rotate_xen_guest_logs.sh /etc/cron.daily/ && mkdir -p /var/log/xen/guest

        # cleanup 
	rm "$NOVA_ZIPBALL"
	rm -rf "$NOVA_SOURCES"
	rm -f /etc/firstboot.d/95-openstack-firstboot
	rm -f /etc/firstboot.d/05-openstack-notify
}

case $1 in
    start)  start ;;
esac	
