#!/bin/bash
##
# Run reboot the server to complete install

set -eu

start() {
  # Install XenServer Patch
  rm -f /etc/firstboot.d/data/firstboot_in_progress
  /root/hotfixes/apply-patches.sh
}

case $1 in
    start)  start ;;
esac
